[project]
name = "stocksim"
version = "0.1.0"
description = "Monte Carlo Stock Simulation (Policies A/B)"
requires-python = ">=3.10"
dependencies = [
"PySide6>=6.7",
"pydantic>=2.7",
"numpy>=1.26",
"PyYAML>=6.0"
]